version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build started on `date`
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain xxxxx --domain-owner xxxxx --query authorizationToken --output text`
      - mvn clean compile package install -DskipTests
      - pip3 install awscli --upgrade --user
  post_build:
    commands:
      - echo Build completed on `date`
      - ls
artifacts:
  files:
    - '**/*.jar'
    - appspec.yml
    - scripts/*.sh
  discard-paths: yes